### ISSUE TITLE
Make the -mem switch idiot-proof

### ISSUE THREAD

**Issue by IanHeywood** [paoloserra/crystalball#18]
I just ran crystalball with `-mem 90` forgetting that I should specify a fraction and not a wsclean-style percentage.

I didn't spot the

```
expected memory usage = 5081.70 GB
``` 

message until I had caused the server to grind to a halt for some time. Entirely my fault of course, but making this idiot-proof by capping this parameter at 1 shouldn't be too much effort!

Cheers.

**Comment by paoloserra** [comment]
:D !!! will do

**Comment by paoloserra** [comment]
@sjperkins I'm going to fix this before making a new release.
