### ISSUE TITLE
Coordinate frames from WSClean are unsensical

### ISSUE THREAD

**Issue by bennahugo** [paoloserra/crystalball#21]
There are problems with the RA being dumped by WSClean. These are supposed to be positive for PKSB0407-65. I'm not sure under what circumstances the signs are being flipped though. Anybody else seen this?

```
Format = Name, Type, Ra, Dec, I, SpectralIndex, LogarithmicSI, ReferenceFrequency='815867187.5', MajorAxis, MinorAxis, Orientation
s0c0,POINT,-04:19:21.257,-65.27.15.463,0.00578103041577101,[-0.012603071675677,0.0551163169235547,-0.177074831553825],false,815867187.5,,,
s0c1,POINT,-04:19:21.258,-65.27.13.863,0.0179765574516339,[-0.0530653687309229,0.165829193277225,-0.245797973228323],false,815867187.5,,,
s0c2,POINT,-04:20:31.366,-65.22.26.836,0.000805752230077412,[-0.00111250733803891,0.00362402423852994,-0.0567354018452293],false,815867187.5,,,
s0c3,POINT,-04:20:31.622,-65.22.26.837,0.0076966711492627,[-0.0150257870986399,0.0794660345667744,-0.438323479127165],false,815867187.5,,,
```

**Comment by KshitijT** [comment]
There is an internal conversion in crysralball, I think.

**Comment by KshitijT** [comment]
And yes, I also saw it for several sources. Initially thought it might have been a multiscale issue, but is general. 
P.S. If using Crystalball with ds9 region files, use only degree format - not sexagesimal, as you have above.

**Comment by bennahugo** [comment]
Hmm seems to be running with sexagesimal though. Internally it uses the astropy routines which do accept sexagesimal. However, it is so slow that I switched back to using DDFacet and Montblanc

**Comment by bennahugo** [comment]
I've sent Andre an email to check the coordinates produced by the imager.

**Comment by paoloserra** [comment]
@bennahugo any news on this? I'm also working on a field where the RA values are negative, but Crystalball handles that OK.

So is this an actual issue or just an ugly thing we can put up with?
