### ISSUE TITLE
Crystalball can't open region file

### ISSUE THREAD

**Issue by KshitijT** [paoloserra/crystalball#25]
I am running : 

```
crystalball -sm sources.txt -w 'myreg.reg' -sp -o MODEL_DATA_SPECIAL MYMS.MS

```

with release 0.2.0 of Crystalball, in a python 3 virtualenv.

Now this seems to work fine until one specifies the region file, when it crashes, with the following error:

```
Traceback (most recent call last):
  File "/home/kshitij/p3-venv/bin/crystalball", line 11, in <module>
    load_entry_point('crystalball', 'console_scripts', 'crystalball')()
  File "/home/kshitij/crystalball/Crystalball/crystalball.py", line 161, in predict
    return _predict(args)
  File "/home/kshitij/crystalball/Crystalball/crystalball.py", line 174, in _predict
    tmpfile.write(regfile.read().lower())
  File "/home/kshitij/p3-venv/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'


```

Python 2 to 3 conversion woes?

**Comment by sjperkins** [comment]
Does the following resolve the issue (as suggested by https://stackoverflow.com/a/45269679/1611416)

```python
tmpfile.write(regfile.read().lower().encode())
```

and would you be willing to submit a PR with the fix?

**Comment by KshitijT** [comment]
The answers are, respectively,:
1) I'll check it out.
2) Yes.

**Comment by sjperkins** [comment]
Thank you kindly Dr Thorat!

**Comment by KshitijT** [comment]
Looks like that works, thanks for the fix ! I have made the push to the my fork, branch 'trivialfix2', @sjperkins .
