### ISSUE TITLE
Needs field specification functionality

### ISSUE THREAD

**Issue by KshitijT** [paoloserra/crystalball#29]
It would be nice if Crystalball could be run with field specifications.
Case in point, I am running Crystalball on a non-split dataset, which has three fields. Only one of them is the target field - but Crystalball ran for all three fields. 
Can we have a "field" switch to bypass this?

**Comment by o-smirnov** [comment]
Yes and can we please have this specifiable by name **and** number for a change. :)

**Comment by paoloserra** [comment]
https://github.com/paoloserra/crystalball/pull/30
