### ISSUE TITLE
Can't read higher-order polynomial models

### ISSUE THREAD

**Issue by o-smirnov** [paoloserra/crystalball#3]
Got a component line like this, which makes the script fall over:

```
Format = Name, Type, Ra, Dec, I, SpectralIndex, LogarithmicSI, ReferenceFrequency='1403434570.3125', MajorAxis, MinorAxis, Orientation
s0c0,POINT,05:38:09.353,-69.59.08.609,1.11109865506291e-05,[-0.000135827406408961,0.000333375129810983,0.000334457654471637],false,1403434570.3125,,,
s0c1,POINT,05:34:00.87,-69.58.45.927,3.29730947499324e-05,[-0.000555701297127677,0.0019426728245186,0.00483373990392782],false,1403434570.3125,,,
```

I can see the issue is here: https://github.com/paoloserra/crystalball/blob/master/Crystalball/crystalball.py#L140

as it ends up splitting the coefficients inside "[ ]" into multiple columns:
```
(Pdb) wsclean_sources[0]
array(['s0c0', 'POINT', '05:38:09.353', '-69:59:08.609',
       '1.11109865506291e-05', '[-0.000135827406408961',
       '0.000333375129810983', '0.000334457654471637]', 'false',
       '1403434570.3125', '', '', ''], dtype='|S22')
(Pdb) 
```
But I'm not sure how this can be dealt with with the standard numpy readers -- might need to write our own bit of code to parse line by line instead....

**Comment by paoloserra** [comment]
right, let me see what I can do

**Comment by sjperkins** [comment]
Take a look at the [wsclean sky model](https://codex-africanus.readthedocs.io/en/latest/model-api.html#wsclean-spectral-model) section in codex.

This should be handled correctly by the `load` function and there're also numpy + dask `spectra` functions which produce a spectral model from wsclean polynomials described ni the columns produced by `load`.

Test cases for the above functionality are [here](https://github.com/ska-sa/codex-africanus/tree/master/africanus/model/wsclean/tests)

**Comment by o-smirnov** [comment]
Yeah, I can confirm that changing the regex to ``r"(?P<secs>\d+\.?\d*)")`` works. So, @sjperkins to fix africanus, and @paoloserra will fix crystalball to use the africanus load function?

**Comment by paoloserra** [comment]
yep, working on that

**Comment by sjperkins** [comment]
Working on the regex now

**Comment by paoloserra** [comment]
Fixed by https://github.com/paoloserra/crystalball/commit/7b68f92c205d8ddfe4070fa2b463688ee7a96ddf once @sjperkins fixes codex-africanus . Let's keep this open until then.

Sorry @o-smirnov for not seeing https://github.com/paoloserra/crystalball/pull/4 !

**Comment by sjperkins** [comment]
https://github.com/ska-sa/codex-africanus/pull/91 merged

**Comment by paoloserra** [comment]
thanks @sjperkins , works for me.

@SpheMakh can you please make sure that this fixes of both codex-africanus and crystalball make it into Stimela?
