### ISSUE TITLE
Wrong reading of WSclean source list

### ISSUE THREAD

**Issue by paoloserra** [paoloserra/crystalball#31]
Crystalball 0.2.0 does not read the WSclean source list correctly.

I imaged a field where the brightest continuum source is 60 mJy (point source). Continuum imaging is good, and the 60 mJy source is included in the WSclean source list. Yet, after running Crystalball 0.2.0 and subtracting MODEL from CORRECTED the resulting line cube still has the 60 mJy source in it. Interestingly, all other sources are gone.

Printing the stokes array imported at https://github.com/paoloserra/crystalball/blob/bcd82f1b4fdf8fe0462589363493b907a8ac8e10/Crystalball/crystalball.py#L179-L184 gives odd results: the brightest source is missing, and I see non-zero Q,U,V even though the model is I-only.

I believe the source of the problem is a missing comma in.

https://github.com/paoloserra/crystalball/blob/bcd82f1b4fdf8fe0462589363493b907a8ac8e10/Crystalball/wsclean.py#L131

Will test and report back.

**Comment by paoloserra** [comment]
Problem solved by https://github.com/paoloserra/crystalball/commit/06985bc71ed8067d9f6219b787712f1ed1067327.

This is a major bug in Crystalball 0.2.0 so I suggest we make a new release.

**Comment by sjperkins** [comment]
@paoloserra Apologies I think I introduced this bug. Thanks for fixing.
