### ISSUE TITLE
0.2.1 pypi upload failed

### ISSUE THREAD

**Issue by sjperkins** [paoloserra/crystalball#32]
### Description

1. The version number in setup.py wasn't bumped
2. travis build tag 0.2.1 but tried to upload 0.2.0 to pypi.
3. this failed.

https://travis-ci.org/paoloserra/crystalball/builds/609140069?utm_source=github_status&utm_medium=notification

@SpheMakh I suggest you delete the 0.2.1 tag, bump the version in setup.py and retag 0.2.1

**Comment by SpheMakh** [comment]
Done
